name: jwparticipant
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  # datetime_picker_formfield: ^1.0.0
  flutter_datetime_picker: ^1.3.4
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  cloud_firestore: ^0.13.0+1
  fl_chart: ^0.8.1
  flare_splash_screen: ^2.1.4
  flare_flutter: any
  firebase_auth: ^0.15.4
  google_fonts: ^0.3.5
  vibration: ^1.2.2
  loading: ^1.0.2
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
      - assets/
      - images/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700